<a href="https://colab.research.google.com/github/PradeepKumarM30/WinterSemester2020-21/blob/DeepLearning/FATEXAM/20MAI0030QNO2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
#Load Imports
import numpy as np

In [52]:
#Load Files - This file was created in local machine with some random inputs and not taken from any online dataset
file = np.loadtxt(open("/content/sample_data/data.csv", "rb"), delimiter=",", skiprows=1) 

In [53]:
#Visualising the data 
file

array([[-1., -1.,  0.],
       [-1.,  1.,  1.],
       [ 1., -1.,  1.],
       [ 1.,  1.,  1.]])

In [54]:
#converting rows and columns to each other for vectorisation that will happen later in this code
new_file = file.T

In [55]:
#Now the new file looks like
print(new_file)

[[-1. -1.  1.  1.]
 [-1.  1. -1.  1.]
 [ 0.  1.  1.  1.]]


In [56]:
#Assign train values 
X_train,Y_train = new_file[0:2,:],new_file[2,:] #take the input data from file 

In [57]:
#input snapshot
print(X_train,' ',Y_train)

[[-1. -1.  1.  1.]
 [-1.  1. -1.  1.]]   [0. 1. 1. 1.]


In [58]:
#initialise weight and bias matrix
def initialize_with_zeros(dim):
   
    w = np.zeros((dim,1))
    b = 0
   
    assert(w.shape == (dim, 1))
    assert(isinstance(b, float) or isinstance(b, int))
    
    return w, b

In [59]:
#Sigmoid activation utility
def sigmoid(z):
   
    s = 1/(1+(np.exp(-z)))
    
    return s

In [60]:
def binary_activation(z):
  s = np.zeros(z.shape)
  rows = z.shape[0]
  cols = z.shape[1]
  for x in range(0, rows):
    for y in range(0, cols):
         if z[x,y]  >= 0.2: 
           s[x,y] = 1
         else :
           s[x,y] = 0
  return s

In [61]:
#forward propogation
def propagate(w, b, X, Y):
    
    m = X.shape[1]
    
    A = binary_activation(np.dot(w.T,X)+b)                                   
    cost = (-1/m) * (np.dot(Y,(np.log(A)).T) + np.dot(1-Y,(np.log(1-A)).T))                               
    dw = np.dot(X,(A-Y).T)/m
    db = (1/m) * np.sum(A-Y)

    assert(dw.shape == w.shape)
    assert(db.dtype == float)
    cost = np.squeeze(cost)
    assert(cost.shape == ())
    
    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

In [62]:
#doing the computations
def optimize(w, b, X, Y, num_iterations, learning_rate, print_cost = False):
    
    costs = []
    
    for i in range(num_iterations):
        grads, cost = propagate(w,b,X,Y)
        
        dw = grads["dw"]
        db = grads["db"]
        
        w = w - (learning_rate * dw)
        b = b - (learning_rate * db)
        
        if i % 100 == 0:
            costs.append(cost)
        
        if print_cost and i % 10 == 0:
            print ("Cost after iteration %i: %f" %(i, cost))
    
    params = {"w": w,
              "b": b}
    
    grads = {"dw": dw,
             "db": db}
    
    return params, grads, costs

In [63]:
#Perceptron driver code
def perceptron(X_train, Y_train, num_iterations, learning_rate = 0.5):
   
    w,b = initialize_with_zeros(X_train.shape[0])

    parameters, grads, costs = optimize(w, b, X_train, Y_train, num_iterations, learning_rate)
    
    w = parameters["w"]
    b = parameters["b"]
    
#    Y_prediction_test = predict(w, b, X_test)
    Y_prediction_train = predict(w, b, X_train)

    print("train accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_train - Y_train)) * 100))
#    print("test accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_test - Y_test)) * 100))

    
    d = {"costs": costs, 
         "Y_prediction_train" : Y_prediction_train, 
         "w" : w, 
         "b" : b,
         "learning_rate" : learning_rate,
         "num_iterations": num_iterations}
    
    return d

In [64]:
#function to predict models performance
def predict(w, b, X):
    
    m = X.shape[1]
    Y_prediction = np.zeros((1,m))
    w = w.reshape(X.shape[0], 1)
    
    A = binary_activation(np.dot(w.T,X)+b)
    
    for i in range(A.shape[1]):
        Y_prediction[:,i] = 1 if A[:,i] > 0.52 else 0
    
    assert(Y_prediction.shape == (1, m))
    
    return Y_prediction

In [65]:
#the main driver code
print(" M PRADEEP KUMAR - 20MAI0030")
output_dict = perceptron(X_train,Y_train,2,1)
print(output_dict)

 M PRADEEP KUMAR - 20MAI0030
train accuracy: 100.0 %
{'costs': [array(nan)], 'Y_prediction_train': array([[0., 1., 1., 1.]]), 'w': array([[0.5],
       [0.5]]), 'b': 0.5, 'learning_rate': 1, 'num_iterations': 2}


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys
